### ISSUE TITLE
Looking to contribute 

### ISSUE THREAD

**Issue by borosilicate** [Benchling-Open-Source/allotropy#12]
Hello Benchling team. I was at bench talk earlier this week and heard about the allotropy project you are working on. I'm eager to contribute. Do I need to sign anything to begin contributing?

**Comment by LimulusPolyphemus** [comment]
@borosilicate that is fantastic to hear!

As introduction, I'm Joe and I'm the product manager at Benchling supporting our instrument adapter development.

Yes, there is a contributor license agreement - which I'm now realizing is not posted on the Contributing ReadMe. I'll get that up there.

Is there a particular instrument type or instrument model in particular that you're interested in working on?

**Comment by borosilicate** [comment]
There is no model in particular I need done. I'm just planning on working on which ever you're team would prefer to have done first.

**Comment by LimulusPolyphemus** [comment]
That's great! Would you be willing to email me: joe.negri@benchling.com and I'll send you a copy of the Contributor License Agreement to sign.
