### ISSUE TITLE
Issue generating schemas via hatch run scripts:generate-schemas

### ISSUE THREAD

**Issue by keithmacaulay** [Benchling-Open-Source/allotropy#173]
When running `hatch run scripts:generate-schemas`, I got the following error:

> Generating` models for schema: pcr/BENCHLING/2023/09/qpcr.json...
> Traceback (most recent call last):
>   File "/allotropy/scripts/generate_schemas.py", line 10, in <module>
>     generate_schemas(ROOT_DIR)
>   File "/allotropy/src/allotropy/allotrope/schema_parser/generate_schemas.py", line 115, in generate_schemas
>     lint_file(model_path)
>   File "/allotropy/src/allotropy/allotrope/schema_parser/generate_schemas.py", line 52, in lint_file
>     subprocess.check_call(
>   File "/.pyenv/versions/3.11.0/lib/python3.11/subprocess.py", line 413, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command 'ruff /allotropy/src/allotropy/allotrope/models/pcr_benchling_2023_09_qpcr.py --fix' returned non-zero exit status 1.

Are there any additional steps to follow in order for this to work, besides the ones described in the readme?

**Comment by nathan-stender** [comment]
Hi Keith.

This error points to a problem when generating the schemas, or a difference in ruff (which shouldn't really happen with hatch)

Do you have any modifications to the json schemas?  If not, I would be very curious to see a branch that runs into this issue.
